#!/usr/bin/env python3
import json, html, shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parent; OUT=ROOT/'_site'; CONTENT=ROOT/'content'; RES=CONTENT/'resources'
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def esc(v): return html.escape(str(v),quote=True)
def icon(n):
 d={'headphones':'<path d="M4 13a8 8 0 0 1 16 0"/><path d="M4 13v5a2 2 0 0 0 2 2h2v-7H4z"/><path d="M20 13v5a2 2 0 0 1-2 2h-2v-7h4z"/>','audio':'<path d="M4 10v4M8 7v10M12 4v16M16 7v10M20 10v4"/>','news':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h5M7 13h10M7 16h10M15 9h2"/>','community':'<path d="M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM16 10a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/><path d="M3 19c0-3 2.2-5 5-5s5 2 5 5M13 14c.8-.7 1.8-1 3-1 2.7 0 5 1.8 5 4.5"/>','puzzle':'<path d="M8 3h5a2 2 0 1 1 4 0h4v6a2 2 0 1 0 0 4v8h-7a2 2 0 1 0-4 0H3v-7a2 2 0 1 0 0-4V3h5z"/>','computer':'<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 20h8M12 16v4"/>','graduation':'<path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11v5c3 3 9 3 12 0v-5M22 9v6"/>','pen':'<path d="M4 20h4L19 9l-4-4L4 16v4zM13.5 6.5l4 4"/>','mic':'<path d="M12 3a4 4 0 0 0-4 4v5a4 4 0 0 0 8 0V7a4 4 0 0 0-4-4zM5 11v1a7 7 0 0 0 14 0v-1M12 19v3M9 22h6"/>','search':'<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>','book':'<path d="M3 5a9 9 0 0 1 9 2v13a9 9 0 0 0-9-2zM21 5a9 9 0 0 0-9 2v13a9 9 0 0 1 9-2z"/>'}
 return '<svg viewBox="0 0 24 24" aria-hidden="true">'+d.get(n,d['book'])+'</svg>'
def nav(cur):
 items=[('Home','index.html','home'),('English Resources','english-learning-resources.html','resources'),('Academic English','academic-english.html','academic'),('Dictionaries','dictionaries.html','dictionaries'),('Communities','communities.html','communities'),('About','about.html','about'),('Contact','contact.html','contact')]
 links=''.join(f'<a href="{h}" class="{"active" if k==cur else ""}">{t}</a>' for t,h,k in items)
 return f'<header class="site-header"><div class="nav-wrap"><a class="brand" href="index.html"><span class="brand-mark">SH</span><span>Samira’s English Hub</span></a><button class="nav-toggle" type="button" aria-expanded="false">Menu</button><nav class="main-nav">{links}</nav></div></header>'
def shell(title,desc,body,cur):
 site=load(CONTENT/'site.json'); full=title if title==site['site_title'] else f"{title} | {site['site_title']}"
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(full)}</title><meta name="description" content="{esc(desc)}"><meta name="theme-color" content="#315f72"><link rel="stylesheet" href="assets/styles.css"></head><body><a class="skip-link" href="#main">Skip to content</a>{nav(cur)}<main id="main">{body}</main><footer class="site-footer"><div><strong>Samira’s English Hub</strong><p>Practical English for study, work and everyday life.</p></div><div class="footer-links"><a href="about.html">About</a><a href="contact.html">Contact</a><a href="admin/">Site editor</a></div><p class="footer-note">External learning resources remain the property of their respective publishers.</p></footer><script src="assets/app.js"></script></body></html>'
def resources(): return [load(p) for p in sorted(RES.glob('*.json'))]
def card(r):
 tags=''.join(f'<span class="tag">{esc(x)}</span>' for x in r.get('tags',[])[:3]); skills=' '.join(r.get('skills',[])); levels=' '.join(r.get('levels',[])); search=' '.join([r.get('title',''),r.get('description',''),*r.get('tags',[]),*r.get('skills',[]),*r.get('levels',[])]).lower()
 return f'<article class="resource-card" data-skills="{esc(skills)}" data-levels="{esc(levels)}" data-australian="{str(bool(r.get("australian"))).lower()}" data-search="{esc(search)}"><div class="resource-icon">{icon(r.get("icon","book"))}</div><div class="resource-content"><div class="tags">{tags}</div><h3>{esc(r["title"])}</h3><p>{esc(r["description"])}</p></div><a class="card-link" href="{esc(r["url"])}" target="_blank" rel="noopener noreferrer">Visit resource →</a></article>'
def grid(rs): return '<div class="resource-grid">'+''.join(card(r) for r in rs)+'</div>'
def home(site,rs):
 skills=[('listen','Listen','headphones','Podcasts, videos and real-world listening practice.'),('speak','Speak','mic','Pronunciation, conversation and spoken English.'),('read','Read','book','Stories, news and reading comprehension.'),('write','Write','pen','Writing, grammar and sentence-building practice.'),('academic','Academic English','graduation','Study skills, assignments and academic writing.'),('practise','Practise','puzzle','Interactive worksheets, quizzes and games.')]
 tiles=''.join(f'<a class="skill-tile" href="{"academic-english.html" if k=="academic" else "english-learning-resources.html#"+k}"><div class="skill-icon">{icon(i)}</div><h3>{t}</h3><p>{d}</p><span>Explore →</span></a>' for k,t,i,d in skills)
 aus=[r for r in rs if r.get('australian') and r.get('collection')=='english'][:3]; feat=[r for r in rs if r.get('featured')][:6]
 audio=f'<div class="audio-welcome">{icon("audio")}<div><strong>Listen to Samira’s welcome</strong><audio controls src="{esc(site["welcome_audio"])}"></audio></div></div>' if site.get('welcome_audio') else ''
 b=f'<section class="hero"><div><span class="eyebrow">A learning hub for adult English learners</span><h1>{esc(site["site_title"])}</h1><p class="hero-tagline">{esc(site["tagline"])}</p><p class="hero-intro">{esc(site["hero_intro"])}</p><div class="hero-actions"><a class="btn primary" href="english-learning-resources.html">Start learning</a><a class="btn secondary" href="academic-english.html">Academic English</a></div>{audio}</div><div class="hero-panel"><span class="panel-label">Choose your path</span><div class="mini-paths"><span>Listen</span><span>Speak</span><span>Read</span><span>Write</span><span>Study</span><span>Practise</span></div><p>Search and filter trusted resources by skill and level.</p></div></section>'
 b+=f'<section class="section"><div class="section-heading"><span class="eyebrow">Start here</span><h2>What would you like to practise today?</h2><p>Choose a skill and go straight to resources that match your goal.</p></div><div class="skill-grid">{tiles}</div></section>'
 if aus:b+=f'<section class="section soft"><div class="section-heading"><span class="eyebrow">English in context</span><h2>English for life in Australia</h2><p>Build practical English while learning about Australian life, news and communication.</p></div>{grid(aus)}</section>'
 b+=f'<section class="section"><div class="section-heading split"><div><span class="eyebrow">Handpicked</span><h2>Featured resources</h2></div><a class="text-link" href="english-learning-resources.html">View all resources →</a></div>{grid(feat)}</section><section class="section soft try-today"><div><span class="eyebrow">A small step</span><h2>Try something today</h2><p>Listen to one short item, learn five useful words, or complete one interactive activity.</p></div><a class="btn primary" href="english-learning-resources.html#practise">Find an activity</a></section><section class="section about-preview"><span class="eyebrow">About this site</span><h2>A clearer way to find English-learning resources</h2><p>{esc(site["about_short"])}</p><a class="text-link" href="about.html">About Samira’s English Hub →</a></section>'
 return shell(site['site_title'],site['tagline'],b,'home')
def library(rs):
 rs=[r for r in rs if r.get('collection')=='english']; anchors='<div class="anchor-nav">'+''.join(f'<a href="#{x}">{x.title() if x!="practise" else "Practise"}</a>' for x in ['listen','speak','read','write','practise'])+'<a href="academic-english.html">Academic English</a></div>'
 filters=f'<div class="filters"><label class="search-field"><span>Search</span><div class="search-box">{icon("search")}<input id="resourceSearch" type="search" placeholder="Search resources..."></div></label><label><span>Skill</span><select id="skillFilter"><option value="all">All skills</option><option value="listen">Listening</option><option value="speak">Speaking</option><option value="read">Reading</option><option value="write">Writing</option><option value="practise">Interactive practice</option></select></label><label><span>Level</span><select id="levelFilter"><option value="all">All levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label class="check-row"><input id="australianFilter" type="checkbox"><span>Australian English</span></label></div><p class="result-count" id="resultCount"></p>'
 b='<section class="page-hero"><span class="eyebrow">Resource library</span><h1>English Learning Resources</h1><p>Search by skill or level, or choose a learning path below.</p></section>'+anchors+'<section class="section compact">'+filters+grid(rs)+'</section>'
 return shell('English Learning Resources','Handpicked resources for listening, speaking, reading, writing and interactive English practice.',b,'resources')
def collection(title,intro,rs,kind,cur): return shell(title,intro,f'<section class="page-hero"><span class="eyebrow">Curated resources</span><h1>{title}</h1><p>{intro}</p></section><section class="section compact">{grid([r for r in rs if r.get("collection")==kind])}</section>',cur)
def write(p,s): p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding='utf-8')
def main():
 if OUT.exists():shutil.rmtree(OUT)
 OUT.mkdir(); site=load(CONTENT/'site.json');rs=resources();write(OUT/'index.html',home(site,rs));write(OUT/'english-learning-resources.html',library(rs));write(OUT/'academic-english.html',collection('Academic English','Build academic writing, study and university communication skills with carefully selected resources.',rs,'academic','academic'));write(OUT/'dictionaries.html',collection('Dictionaries & Vocabulary','Use learner-friendly dictionaries and vocabulary tools to understand words, pronunciation and natural usage.',rs,'dictionary','dictionaries'));write(OUT/'communities.html',collection('English Learning Communities','Practise English with other learners through discussions, peer interaction and language exchange.',rs,'community','communities'))
 about=f'<section class="page-hero narrow"><span class="eyebrow">About</span><h1>About Samira’s English Hub</h1><p>{esc(site["about_short"])}</p></section><section class="section prose"><h2>Why I created this site</h2><p>{esc(site["about_long"])}</p><h2>How to use it</h2><p>Start with a skill on the homepage, use the filters, and choose one activity at a time.</p></section>';write(OUT/'about.html',shell('About','About Samira’s English Hub.',about,'about'))
 contact=f'<section class="page-hero narrow"><span class="eyebrow">Contact</span><h1>Questions or suggestions?</h1><p>Suggest a useful English-learning resource or get in touch.</p><a class="btn primary" href="{esc(site.get("contact_url","#"))}" target="_blank" rel="noopener">Open contact form</a></section>';write(OUT/'contact.html',shell('Contact','Contact Samira’s English Hub.',contact,'contact'))
 shutil.copytree(ROOT/'assets',OUT/'assets');shutil.copytree(ROOT/'admin',OUT/'admin');write(OUT/'.nojekyll','');print(f'Built {len(rs)} resources')
if __name__=='__main__':main()
